// <auto-generated />
using C_Scherp_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C_Scherp_Api.Migrations
{
    [DbContext(typeof(CScherpContext))]
    [Migration("20250214085422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("C_Scherp_Api.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("DietaryFiber")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dietary_fiber");

                    b.Property<decimal>("Energy")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Salt")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SaturatedFat")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("saturated_fat");

                    b.Property<decimal>("Sugars")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnsaturatedFat")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("unsaturated_fat");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
